# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='main.BillRegion', verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
    ]
