# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161019_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='images',
            new_name='image',
        ),
    ]
