# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161019_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billregion',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='billregion',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
